[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "cd frontend && npm ci --production=false"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm run serve"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
